name: Android Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 1
      - name: Checkout code
        uses: actions/checkout@v2
      # 2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Increment versionCode
        run: |
          #!/bin/bash

          gradleFilePath="app/build.gradle"
          
          versionCode=$(grep versionCode $gradleFilePath | awk '{print $2}')
          newVersionCode=$((versionCode+1))
          
          echo "Current versionCode: $versionCode"
          echo "New versionCode: $newVersionCode"
          
          sed -i "s/versionCode $versionCode/versionCode $newVersionCode/" $gradleFilePath
          
          echo "Updated build.gradle:"
          cat $gradleFilePath

      - name: Configure Git
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "GitHub Actions"

      - name: Commit version code increment
        run: |
          git add app/build.gradle
          git commit -m "Increment versionCode for build" || echo "No changes to commit"
        
      - name: Push changes
        run: |
          git push

      - name: Generate Release APK
        run: ./gradlew assembleRelease
      # 3
      - name: Sign APK
        uses: r0adkll/sign-android-release@v1
        # ID used to access action output
        id: sign_app
        with:
          releaseDirectory: app/build/outputs/apk/release
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}
      
      # 3.5 Rename signed APK file
      - name: Rename APK file
        run: mv ${{ steps.sign_app.outputs.signedReleaseFile }} app/build/outputs/apk/release/release-signed.apk
  
      # 4
      - uses: actions/upload-artifact@master
        with:
          name: release.apk
          path: app/build/outputs/apk/release/release-signed.apk
      # 5
      - uses: actions/upload-artifact@master
        with:
          name: mapping.txt
          path: app/build/outputs/mapping/release/mapping.txt
